CREATE TABLE `models_page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `banner_title` varchar(255) DEFAULT NULL,
  `banner_url_desktop` text,
  `banner_url_mobile` text,
  `banner_description` text,
  `banner_info_heading_1` varchar(255) DEFAULT NULL,
  `banner_info_desc_1` varchar(255) DEFAULT NULL,
  `banner_info_heading_2` varchar(255) DEFAULT NULL,
  `banner_info_desc_2` varchar(255) DEFAULT NULL,
  `banner_info_heading_3` varchar(255) DEFAULT NULL,
  `banner_info_desc_3` varchar(255) DEFAULT NULL,
  `banner_info_heading_4` varchar(255) DEFAULT NULL,
  `banner_info_desc_4` varchar(255) DEFAULT NULL,
  `banner_white` varchar(10) DEFAULT 'false',
  
  `section_heading` varchar(255) DEFAULT NULL,
  `photo_url_desktop` text,
  `photo_url_mobile` text,
  
  `car_info_1_heading` varchar(255) DEFAULT NULL,
  `car_info_1_desc` text,
  `car_info_1_url` text,
  `car_info_2_heading` varchar(255) DEFAULT NULL,
  `car_info_2_desc` text,
  `car_info_2_url` text,
  `car_info_3_heading` varchar(255) DEFAULT NULL,
  `car_info_3_desc` text,
  `car_info_3_url` text,
  
  `car_info_banner_1_url` text,
  `car_info_banner_1_h1` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d1` varchar(255) DEFAULT NULL,
  `car_info_banner_1_h2` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d2` varchar(255) DEFAULT NULL,
  `car_info_banner_1_h3` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d3` varchar(255) DEFAULT NULL,
  
  `beyond_1_heading` varchar(255) DEFAULT NULL,
  `beyond_1_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_1_description` text,
  `beyond_1_black` varchar(10) DEFAULT 'false',
  
  `ep_url_1` text,
  `ep_heading_1` varchar(255) DEFAULT NULL,
  `ep_desc_1` text,
  `ep_stat_h11` varchar(255) DEFAULT NULL,
  `ep_stat_h12` varchar(255) DEFAULT NULL,
  `ep_stat_h13` varchar(255) DEFAULT NULL,
  `ep_stat_d11` varchar(255) DEFAULT NULL,
  `ep_stat_d12` varchar(255) DEFAULT NULL,
  `ep_stat_d13` varchar(255) DEFAULT NULL,
  
  `ep_url_2` text,
  `ep_heading_2` varchar(255) DEFAULT NULL,
  `ep_desc_2` text,
  `ep_stat_h21` varchar(255) DEFAULT NULL,
  `ep_stat_h22` varchar(255) DEFAULT NULL,
  `ep_stat_h23` varchar(255) DEFAULT NULL,
  `ep_stat_d21` varchar(255) DEFAULT NULL,
  `ep_stat_d22` varchar(255) DEFAULT NULL,
  `ep_stat_d23` varchar(255) DEFAULT NULL,

  `car_info_banner_2_url` text,
  
  `beyond_2_heading` varchar(255) DEFAULT NULL,
  `beyond_2_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_2_description` text,
  `beyond_2_black` varchar(10) DEFAULT 'true',
  
  `car_info_4_heading` varchar(255) DEFAULT NULL,
  `car_info_4_desc` text,
  `car_info_4_url` text,
  `car_info_5_heading` varchar(255) DEFAULT NULL,
  `car_info_5_desc` text,
  `car_info_5_url` text,
  `car_info_6_heading` varchar(255) DEFAULT NULL,
  `car_info_6_desc` text,
  `car_info_6_url` text,

  `infovideo_url` text,
  `infovideo_semi_heading` varchar(255) DEFAULT NULL,
  `infovideo_heading` varchar(255) DEFAULT NULL,
  `infovideo_description` text,
  
  `beyond_3_heading` varchar(255) DEFAULT NULL,
  `beyond_3_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_3_description` text,
  `beyond_3_black` varchar(10) DEFAULT 'false',
  
  `order_now_heading` varchar(255) DEFAULT NULL,
  `order_now_url` text,
  `order_now_black` varchar(10) DEFAULT 'false',

  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `models_page` (
  banner_title, banner_url_desktop, banner_url_mobile, banner_description,
  banner_info_heading_1, banner_info_desc_1,
  banner_info_heading_2, banner_info_desc_2,
  banner_info_heading_3, banner_info_desc_3,
  banner_info_heading_4, banner_info_desc_4,
  banner_white, section_heading,
  photo_url_desktop, photo_url_mobile,
  car_info_1_heading, car_info_1_desc, car_info_1_url,
  car_info_2_heading, car_info_2_desc, car_info_2_url,
  car_info_3_heading, car_info_3_desc, car_info_3_url,
  car_info_banner_1_url, car_info_banner_1_h1, car_info_banner_1_d1, car_info_banner_1_h2, car_info_banner_1_d2, car_info_banner_1_h3, car_info_banner_1_d3,
  beyond_1_heading, beyond_1_semi_heading, beyond_1_description, beyond_1_black,
  ep_url_1, ep_heading_1, ep_desc_1, ep_stat_h11, ep_stat_h12, ep_stat_h13, ep_stat_d11, ep_stat_d12, ep_stat_d13,
  ep_url_2, ep_heading_2, ep_desc_2, ep_stat_h21, ep_stat_h22, ep_stat_h23, ep_stat_d21, ep_stat_d22, ep_stat_d23,
  car_info_banner_2_url,
  beyond_2_heading, beyond_2_semi_heading, beyond_2_description, beyond_2_black,
  car_info_4_heading, car_info_4_desc, car_info_4_url,
  car_info_5_heading, car_info_5_desc, car_info_5_url,
  car_info_6_heading, car_info_6_desc, car_info_6_url,
  infovideo_url, infovideo_semi_heading, infovideo_heading, infovideo_description,
  beyond_3_heading, beyond_3_semi_heading, beyond_3_description, beyond_3_black,
  order_now_heading, order_now_url, order_now_black
) VALUES (
  'Model S',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032623/model-s_aeolii.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032619/model-s-mobile_mjjjt0.jpg',
  'Plaid',
  '396 mi', 'Range (EPA est.)',
  '1.99s', '0-60 mph*',
  '200 mph', 'Top Speed',
  '1,020 hp', 'Peak Power',
  'false', 'Interior of the Future',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032621/interior_x1udcr.jpg', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032622/interior-mobile_c2pm4m.jpg',
  'Stay Connected', 'Instantly connect with multi-device Bluetooth, or fast charge devices with wireless and 36-watt USB-C charging.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032609/stay-connected_izi9zj.jpg',
  'Immersive Sound', 'A 22-speaker, 960-watt audio system with Active Road Noise Reduction offers immersive listening and studio-grade sound quality.', 'https://res.cloudinary.com/doqeslffo/video/upload/v1770032626/Immersive-sound_qmdwto.mp4',
  'Room for Everything', 'With front and rear trunks and fold-flat seats you can fit your bike without taking the wheel off—and your luggage too.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032611/room-for-everything_crfkps.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032620/model-s-blue_drba3h.jpg', '1,020 hp', 'Peak Power', '9.23 s', '@155 mph 1/4 mile', '1.99 s', '0-60 mph*',
  'Beyond Ludicrous', 'Plaid', 'Model S Plaid has the quickest acceleration of any vehicle in production. Updated battery architecture for all Model S trims enables back-to-back track runs without performance degradation. Chat with a Tesla Advisor to learn more about Model S or schedule a demo drive today.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032621/model-s-battery_m3x5mi.jpg', 'Model S', 'Dual Motor All-Wheel Drive unlocks more range than any other vehicle in our current lineup, with insane power and maximum control.', '3.1 s', '405 mi', '670 hp', '0-60 mph', 'Range (EPA est.)', 'Peak Power',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032616/model-s-plaid-battery_xgvsvr.jpg', 'Model S Plaid', 'Maintain 1,000+ horsepower all the way to 200 mph with Tri-Motor All-Wheel Drive, featuring torque vectoring and three independent carbon-sleeved rotors.', '1.99 s*', '396 mi', '1,020 hp', '0-60 mph', 'Range (EPA est.)', 'Peak Power',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032617/models-wave_fs4wpi.jpg',
  'Designed for Efficiency', 'Exterior', 'With a drag coefficient of just .208 Cd, the lowest on the planet, Model S is built for speed, endurance and range. Improved aerodynamics and a wider chassis offer more responsive performance so you can take corners quicker and with more confidence.', 'true',
  'Relentless Performance', 'Staggered, performance wheels and tires keep the car planted and help transfer maximum power down to the road.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032614/relentless-performance_cxvgit.jpg',
  'Optimized Aerodynamics', 'Attention to detail on all exterior surfaces makes Model S the most aerodynamic production car on Earth.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032615/optimized-aerodynamics_vckwbj.jpg',
  'Refined Styling', 'An iconic silhouette meets refreshed, elegant proportions.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032614/refined-styling_lhxn42.jpg',
  'https://res.cloudinary.com/doqeslffo/video/upload/v1770032666/models-range_ybynns.mp4', 'Range', 'Go Anywhere', 'With up to 405 miles of estimated range and access to the world’s largest and most powerful fast charging network, you’ll spend less time plugged in and more time on the road. Chat with a Tesla Advisor to learn more about Model S or schedule a demo drive today.',
  'Future of Driving', 'Autopilot', 'Autopilot enables your car to steer, accelerate and brake automatically within its lane under your active supervision, assisting with the most burdensome parts of driving. With over-the-air software updates, the latest enhancements are available instantly. Chat with a Tesla Advisor to learn more about Model S or schedule a demo drive today.', 'false',
  'Model S', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032618/models-ordernow_iymqn8.jpg', 'false'
);
