-- Model X Table and Data

CREATE TABLE IF NOT EXISTS `modelx_page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `banner_title` varchar(255) DEFAULT NULL,
  `banner_url_desktop` text,
  `banner_url_mobile` text,
  `banner_description` text,
  `banner_info_heading_1` varchar(255) DEFAULT NULL,
  `banner_info_desc_1` varchar(255) DEFAULT NULL,
  `banner_info_heading_2` varchar(255) DEFAULT NULL,
  `banner_info_desc_2` varchar(255) DEFAULT NULL,
  `banner_info_heading_3` varchar(255) DEFAULT NULL,
  `banner_info_desc_3` varchar(255) DEFAULT NULL,
  `banner_info_heading_4` varchar(255) DEFAULT NULL,
  `banner_info_desc_4` varchar(255) DEFAULT NULL,
  `banner_white` varchar(10) DEFAULT 'false',
  
  `section_heading` varchar(255) DEFAULT NULL,
  `photo_url_desktop` text,
  `photo_url_mobile` text,
  
  `car_info_1_heading` varchar(255) DEFAULT NULL,
  `car_info_1_desc` text,
  `car_info_1_url` text,
  `car_info_2_heading` varchar(255) DEFAULT NULL,
  `car_info_2_desc` text,
  `car_info_2_url` text,
  `car_info_3_heading` varchar(255) DEFAULT NULL,
  `car_info_3_desc` text,
  `car_info_3_url` text,
  
  `car_info_banner_1_url` text,
  `car_info_banner_1_h1` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d1` varchar(255) DEFAULT NULL,
  `car_info_banner_1_h2` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d2` varchar(255) DEFAULT NULL,
  `car_info_banner_1_h3` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d3` varchar(255) DEFAULT NULL,
  
  `beyond_1_heading` varchar(255) DEFAULT NULL,
  `beyond_1_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_1_description` text,
  `beyond_1_black` varchar(10) DEFAULT 'false',
  
  `ep_url_1` text,
  `ep_heading_1` varchar(255) DEFAULT NULL,
  `ep_desc_1` text,
  `ep_stat_h11` varchar(255) DEFAULT NULL,
  `ep_stat_h12` varchar(255) DEFAULT NULL,
  `ep_stat_h13` varchar(255) DEFAULT NULL,
  `ep_stat_d11` varchar(255) DEFAULT NULL,
  `ep_stat_d12` varchar(255) DEFAULT NULL,
  `ep_stat_d13` varchar(255) DEFAULT NULL,
  
  `ep_url_2` text,
  `ep_heading_2` varchar(255) DEFAULT NULL,
  `ep_desc_2` text,
  `ep_stat_h21` varchar(255) DEFAULT NULL,
  `ep_stat_h22` varchar(255) DEFAULT NULL,
  `ep_stat_h23` varchar(255) DEFAULT NULL,
  `ep_stat_d21` varchar(255) DEFAULT NULL,
  `ep_stat_d22` varchar(255) DEFAULT NULL,
  `ep_stat_d23` varchar(255) DEFAULT NULL,
  
  `infovideo_1_url` text,
  `infovideo_1_semi` varchar(255) DEFAULT NULL,
  `infovideo_1_heading` varchar(255) DEFAULT NULL,
  `infovideo_1_desc` text,
  
  `car_info_banner_2_url` text,
  
  `beyond_2_heading` varchar(255) DEFAULT NULL,
  `beyond_2_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_2_description` text,
  `beyond_2_black` varchar(10) DEFAULT 'true',
  
  `car_info_4_heading` varchar(255) DEFAULT NULL,
  `car_info_4_desc` text,
  `car_info_4_url` text,
  `car_info_5_heading` varchar(255) DEFAULT NULL,
  `car_info_5_desc` text,
  `car_info_5_url` text,
  `car_info_6_heading` varchar(255) DEFAULT NULL,
  `car_info_6_desc` text,
  `car_info_6_url` text,
  
  `infovideo_2_url` text,
  `infovideo_2_semi` varchar(255) DEFAULT NULL,
  `infovideo_2_heading` varchar(255) DEFAULT NULL,
  `infovideo_2_desc` text,
  
  `beyond_3_heading` varchar(255) DEFAULT NULL,
  `beyond_3_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_3_description` text,
  `beyond_3_black` varchar(10) DEFAULT 'false',
  
  `order_now_heading` varchar(255) DEFAULT NULL,
  `order_now_url` text,
  `order_now_black` varchar(10) DEFAULT 'false',
  
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `modelx_page` (
  banner_title, banner_url_desktop, banner_url_mobile, banner_description,
  banner_info_heading_1, banner_info_desc_1,
  banner_info_heading_2, banner_info_desc_2,
  banner_info_heading_3, banner_info_desc_3,
  banner_info_heading_4, banner_info_desc_4,
  banner_white,
  section_heading, photo_url_desktop, photo_url_mobile,
  car_info_1_heading, car_info_1_desc, car_info_1_url,
  car_info_2_heading, car_info_2_desc, car_info_2_url,
  car_info_3_heading, car_info_3_desc, car_info_3_url,
  car_info_banner_1_url, car_info_banner_1_h1, car_info_banner_1_d1,
  car_info_banner_1_h2, car_info_banner_1_d2,
  car_info_banner_1_h3, car_info_banner_1_d3,
  beyond_1_heading, beyond_1_semi_heading, beyond_1_description, beyond_1_black,
  ep_url_1, ep_heading_1, ep_desc_1, ep_stat_h11, ep_stat_h12, ep_stat_h13, ep_stat_d11, ep_stat_d12, ep_stat_d13,
  ep_url_2, ep_heading_2, ep_desc_2, ep_stat_h21, ep_stat_h22, ep_stat_h23, ep_stat_d21, ep_stat_d22, ep_stat_d23,
  infovideo_1_url, infovideo_1_semi, infovideo_1_heading, infovideo_1_desc,
  car_info_banner_2_url,
  beyond_2_heading, beyond_2_semi_heading, beyond_2_description, beyond_2_black,
  car_info_4_heading, car_info_4_desc, car_info_4_url,
  car_info_5_heading, car_info_5_desc, car_info_5_url,
  car_info_6_heading, car_info_6_desc, car_info_6_url,
  infovideo_2_url, infovideo_2_semi, infovideo_2_heading, infovideo_2_desc,
  beyond_3_heading, beyond_3_semi_heading, beyond_3_description, beyond_3_black,
  order_now_heading, order_now_url, order_now_black
) VALUES (
  'Model X',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041186/model-x_d58hxe.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041182/model-x-mobile_fdxg6n.jpg',
  'Plaid',
  '333 mi', 'Range (EPA est.)',
  '2.5s', '0-60 mph*',
  '9.9s', '1/4 Mile',
  '1,020 hp', 'Peak Power',
  'false',
  'Interior of the Future', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032621/interior_x1udcr.jpg', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032622/interior-mobile_c2pm4m.jpg',
  'Stay Connected', 'Instantly connect with multi-device Bluetooth, or fast charge devices with wireless and 36-watt USB-C charging.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041184/stay-connected_yz8l1p.jpg',
  'Sublime Sound', 'A 22-speaker, 960-watt audio system with Active Road Noise Reduction offers the best listening experience wherever you are.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041180/sublime-sound_wrrsjf.jpg',
  'Room for Everything', 'With front and rear trunks and fold-flat seats you can fit your bike without taking the wheel off—and your luggage too.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032611/room-for-everything_crfkps.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041186/model-x-grey_m1wtyz.jpg', '1,020 hp', 'Peak Power', '9.9s', '1/4 mile', '1.99 s', '0-60 mph*',
  'Beyond Ludicrous', 'Plaid', 'With the most power and quickest acceleration of any SUV, Model X Plaid is the highest performing SUV ever built. Updated battery architecture enables both Long Range and Plaid configurations to complete back-to-back track runs without performance degradation. Chat with a Tesla Advisor to learn more about Model X or schedule a demo drive today.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032621/model-s-battery_m3x5mi.jpg', 'Model X', 'Dual Motor All-Wheel Drive platform has the longest range, and now delivers insane power and acceleration.', '3.8 s', '348 mi', '670 hp', '0-60 mph', 'Range (EPA est.)', 'Peak Power',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032616/model-s-plaid-battery_xgvsvr.jpg', 'Model X Plaid', 'Tri Motor All-Wheel Drive platform with torque vectoring features three independent motors, each with a carbon-sleeved rotor that maintains 1,000+ horsepower all the way to top speed.', '2.5 s*', '333 mi', '1,020 hp', '0-60 mph', 'Range (EPA est.)', 'Peak Power',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041190/even-more-capable_geaoqj.jpg', 'Utility', 'Even More Capable', 'With ample storage and 5,000 lbs of towing capacity, Model X is built for maximum utility. Front doors open and close automatically, Falcon Wing rear doors allow for easier loading and a trailer hitch comes standard, so you can bring your gear with you wherever you go.',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041189/model-x-wave_tduiu7.jpg',
  'Designed for Efficiency', 'Exterior', 'Model X has a drag coefficient of just .24 Cd, the lowest of any production SUV on the planet. Refined aerodynamic elements work together with new wheels and tires to help you travel farther, with sharper handling and better ride comfort.', 'true',
  'Relentless Performance', 'Staggered, performance wheels and tires keep the car planted and help transfer maximum power down to the road.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041181/relentless-performance_gnwcad.jpg',
  'Optimized Aerodynamics', 'Attention to detail on all exterior surfaces makes Model X the most aerodynamic production car on Earth.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041183/optimized-aerodynamics_liqwtf.jpg',
  'Refined Styling', 'Exterior design combines an iconic look with elegant details.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041181/refined-styling_jzeljv.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041189/go-anywhere_wlj4xi.jpg', 'Range', 'Go Anywhere', 'With up to 348 miles of estimated range and access to the world’s largest and most powerful fast charging network, you’ll spend less time plugged in and more time on the road. Chat with a Tesla Advisor to learn more about Model X or schedule a demo drive today.',
  'Future of Driving', 'Autopilot', 'Autopilot enables your car to steer, accelerate and brake automatically within its lane under your active supervision, assisting with the most burdensome parts of driving. With over-the-air software updates, the latest enhancements are available instantly. Chat with a Tesla Advisor to learn more about Model X or schedule a demo drive today.', 'false',
  'Model S', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041182/modelx-ordernow_xvrzcl.jpg', 'false'
);
