-- Model X
CREATE TABLE `modelx_page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `banner_title` varchar(255) DEFAULT NULL,
  `banner_url_desktop` text,
  `banner_url_mobile` text,
  `banner_description` text,
  `banner_info_heading_1` varchar(255) DEFAULT NULL,
  `banner_info_desc_1` varchar(255) DEFAULT NULL,
  `banner_info_heading_2` varchar(255) DEFAULT NULL,
  `banner_info_desc_2` varchar(255) DEFAULT NULL,
  `banner_info_heading_3` varchar(255) DEFAULT NULL,
  `banner_info_desc_3` varchar(255) DEFAULT NULL,
  `banner_info_heading_4` varchar(255) DEFAULT NULL,
  `banner_info_desc_4` varchar(255) DEFAULT NULL,
  `banner_white` varchar(10) DEFAULT 'false',
  
  `section_heading` varchar(255) DEFAULT NULL,
  `photo_url_desktop` text,
  `photo_url_mobile` text,
  
  `car_info_1_heading` varchar(255) DEFAULT NULL,
  `car_info_1_desc` text,
  `car_info_1_url` text,
  `car_info_2_heading` varchar(255) DEFAULT NULL,
  `car_info_2_desc` text,
  `car_info_2_url` text,
  `car_info_3_heading` varchar(255) DEFAULT NULL,
  `car_info_3_desc` text,
  `car_info_3_url` text,
  
  `car_info_banner_1_url` text,
  `car_info_banner_1_h1` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d1` varchar(255) DEFAULT NULL,
  `car_info_banner_1_h2` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d2` varchar(255) DEFAULT NULL,
  `car_info_banner_1_h3` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d3` varchar(255) DEFAULT NULL,
  
  `beyond_1_heading` varchar(255) DEFAULT NULL,
  `beyond_1_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_1_description` text,
  `beyond_1_black` varchar(10) DEFAULT 'false',
  
  `ep_url_1` text,
  `ep_heading_1` varchar(255) DEFAULT NULL,
  `ep_desc_1` text,
  `ep_stat_h11` varchar(255) DEFAULT NULL,
  `ep_stat_h12` varchar(255) DEFAULT NULL,
  `ep_stat_h13` varchar(255) DEFAULT NULL,
  `ep_stat_d11` varchar(255) DEFAULT NULL,
  `ep_stat_d12` varchar(255) DEFAULT NULL,
  `ep_stat_d13` varchar(255) DEFAULT NULL,
  
  `ep_url_2` text,
  `ep_heading_2` varchar(255) DEFAULT NULL,
  `ep_desc_2` text,
  `ep_stat_h21` varchar(255) DEFAULT NULL,
  `ep_stat_h22` varchar(255) DEFAULT NULL,
  `ep_stat_h23` varchar(255) DEFAULT NULL,
  `ep_stat_d21` varchar(255) DEFAULT NULL,
  `ep_stat_d22` varchar(255) DEFAULT NULL,
  `ep_stat_d23` varchar(255) DEFAULT NULL,
  
  `infovideo_1_url` text,
  `infovideo_1_semi` varchar(255) DEFAULT NULL,
  `infovideo_1_heading` varchar(255) DEFAULT NULL,
  `infovideo_1_desc` text,
  
  `car_info_banner_2_url` text,
  
  `beyond_2_heading` varchar(255) DEFAULT NULL,
  `beyond_2_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_2_description` text,
  `beyond_2_black` varchar(10) DEFAULT 'true',
  
  `car_info_4_heading` varchar(255) DEFAULT NULL,
  `car_info_4_desc` text,
  `car_info_4_url` text,
  `car_info_5_heading` varchar(255) DEFAULT NULL,
  `car_info_5_desc` text,
  `car_info_5_url` text,
  `car_info_6_heading` varchar(255) DEFAULT NULL,
  `car_info_6_desc` text,
  `car_info_6_url` text,
  
  `infovideo_2_url` text,
  `infovideo_2_semi` varchar(255) DEFAULT NULL,
  `infovideo_2_heading` varchar(255) DEFAULT NULL,
  `infovideo_2_desc` text,
  
  `beyond_3_heading` varchar(255) DEFAULT NULL,
  `beyond_3_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_3_description` text,
  `beyond_3_black` varchar(10) DEFAULT 'false',
  
  `order_now_heading` varchar(255) DEFAULT NULL,
  `order_now_url` text,
  `order_now_black` varchar(10) DEFAULT 'false',
  
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `modelx_page` (
  banner_title, banner_url_desktop, banner_url_mobile, banner_description,
  banner_info_heading_1, banner_info_desc_1,
  banner_info_heading_2, banner_info_desc_2,
  banner_info_heading_3, banner_info_desc_3,
  banner_info_heading_4, banner_info_desc_4,
  banner_white,
  section_heading, photo_url_desktop, photo_url_mobile,
  car_info_1_heading, car_info_1_desc, car_info_1_url,
  car_info_2_heading, car_info_2_desc, car_info_2_url,
  car_info_3_heading, car_info_3_desc, car_info_3_url,
  car_info_banner_1_url, car_info_banner_1_h1, car_info_banner_1_d1,
  car_info_banner_1_h2, car_info_banner_1_d2,
  car_info_banner_1_h3, car_info_banner_1_d3,
  beyond_1_heading, beyond_1_semi_heading, beyond_1_description, beyond_1_black,
  ep_url_1, ep_heading_1, ep_desc_1, ep_stat_h11, ep_stat_h12, ep_stat_h13, ep_stat_d11, ep_stat_d12, ep_stat_d13,
  ep_url_2, ep_heading_2, ep_desc_2, ep_stat_h21, ep_stat_h22, ep_stat_h23, ep_stat_d21, ep_stat_d22, ep_stat_d23,
  infovideo_1_url, infovideo_1_semi, infovideo_1_heading, infovideo_1_desc,
  car_info_banner_2_url,
  beyond_2_heading, beyond_2_semi_heading, beyond_2_description, beyond_2_black,
  car_info_4_heading, car_info_4_desc, car_info_4_url,
  car_info_5_heading, car_info_5_desc, car_info_5_url,
  car_info_6_heading, car_info_6_desc, car_info_6_url,
  infovideo_2_url, infovideo_2_semi, infovideo_2_heading, infovideo_2_desc,
  beyond_3_heading, beyond_3_semi_heading, beyond_3_description, beyond_3_black,
  order_now_heading, order_now_url, order_now_black
) VALUES (
  'Model X',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041186/model-x_d58hxe.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041182/model-x-mobile_fdxg6n.jpg',
  'Plaid',
  '333 mi', 'Range (EPA est.)',
  '2.5s', '0-60 mph*',
  '9.9s', '1/4 Mile',
  '1,020 hp', 'Peak Power',
  'false',
  'Interior of the Future', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032621/interior_x1udcr.jpg', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032622/interior-mobile_c2pm4m.jpg',
  'Stay Connected', 'Instantly connect with multi-device Bluetooth, or fast charge devices with wireless and 36-watt USB-C charging.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041184/stay-connected_yz8l1p.jpg',
  'Sublime Sound', 'A 22-speaker, 960-watt audio system with Active Road Noise Reduction offers the best listening experience wherever you are.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041180/sublime-sound_wrrsjf.jpg',
  'Room for Everything', 'With front and rear trunks and fold-flat seats you can fit your bike without taking the wheel off—and your luggage too.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770032611/room-for-everything_crfkps.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041186/model-x-grey_m1wtyz.jpg', '1,020 hp', 'Peak Power', '9.9s', '1/4 mile', '1.99 s', '0-60 mph*',
  'Beyond Ludicrous', 'Plaid', 'With the most power and quickest acceleration of any SUV, Model X Plaid is the highest performing SUV ever built. Updated battery architecture enables both Long Range and Plaid configurations to complete back-to-back track runs without performance degradation. Chat with a Tesla Advisor to learn more about Model X or schedule a demo drive today.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032621/model-s-battery_m3x5mi.jpg', 'Model X', 'Dual Motor All-Wheel Drive platform has the longest range, and now delivers insane power and acceleration.', '3.8 s', '348 mi', '670 hp', '0-60 mph', 'Range (EPA est.)', 'Peak Power',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770032616/model-s-plaid-battery_xgvsvr.jpg', 'Model X Plaid', 'Tri Motor All-Wheel Drive platform with torque vectoring features three independent motors, each with a carbon-sleeved rotor that maintains 1,000+ horsepower all the way to top speed.', '2.5 s*', '333 mi', '1,020 hp', '0-60 mph', 'Range (EPA est.)', 'Peak Power',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041190/even-more-capable_geaoqj.jpg', 'Utility', 'Even More Capable', 'With ample storage and 5,000 lbs of towing capacity, Model X is built for maximum utility. Front doors open and close automatically, Falcon Wing rear doors allow for easier loading and a trailer hitch comes standard, so you can bring your gear with you wherever you go.',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041189/model-x-wave_tduiu7.jpg',
  'Designed for Efficiency', 'Exterior', 'Model X has a drag coefficient of just .24 Cd, the lowest of any production SUV on the planet. Refined aerodynamic elements work together with new wheels and tires to help you travel farther, with sharper handling and better ride comfort.', 'true',
  'Relentless Performance', 'Staggered, performance wheels and tires keep the car planted and help transfer maximum power down to the road.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041181/relentless-performance_gnwcad.jpg',
  'Optimized Aerodynamics', 'Attention to detail on all exterior surfaces makes Model X the most aerodynamic production car on Earth.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041183/optimized-aerodynamics_liqwtf.jpg',
  'Refined Styling', 'Exterior design combines an iconic look with elegant details.', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041181/refined-styling_jzeljv.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770041189/go-anywhere_wlj4xi.jpg', 'Range', 'Go Anywhere', 'With up to 348 miles of estimated range and access to the world’s largest and most powerful fast charging network, you’ll spend less time plugged in and more time on the road. Chat with a Tesla Advisor to learn more about Model X or schedule a demo drive today.',
  'Future of Driving', 'Autopilot', 'Autopilot enables your car to steer, accelerate and brake automatically within its lane under your active supervision, assisting with the most burdensome parts of driving. With over-the-air software updates, the latest enhancements are available instantly. Chat with a Tesla Advisor to learn more about Model X or schedule a demo drive today.', 'false',
  'Model S', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770041182/modelx-ordernow_xvrzcl.jpg', 'false'
);

-- Model Y
CREATE TABLE `modely_page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `banner_title` varchar(255) DEFAULT NULL,
  `banner_url_desktop` text,
  `banner_url_mobile` text,
  `banner_description` text,
  `banner_info_heading_1` varchar(255) DEFAULT NULL,
  `banner_info_desc_1` varchar(255) DEFAULT NULL,
  `banner_info_heading_2` varchar(255) DEFAULT NULL,
  `banner_info_desc_2` varchar(255) DEFAULT NULL,
  `banner_info_heading_3` varchar(255) DEFAULT NULL,
  `banner_info_desc_3` varchar(255) DEFAULT NULL,
  `banner_info_heading_4` varchar(255) DEFAULT NULL,
  `banner_info_desc_4` varchar(255) DEFAULT NULL,
  `banner_white` varchar(10) DEFAULT 'true',
  
  `infovideo_1_url` text,
  `infovideo_1_semi` varchar(255) DEFAULT NULL,
  `infovideo_1_heading` varchar(255) DEFAULT NULL,
  `infovideo_1_desc` text,
  
  `beyond_1_heading` varchar(255) DEFAULT NULL,
  `beyond_1_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_1_description` text,
  `beyond_1_black` varchar(10) DEFAULT 'false',
  
  `car_info_banner_1_url` text,
  `car_info_banner_1_h1` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d1` varchar(255) DEFAULT NULL,
  `car_info_banner_1_h2` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d2` varchar(255) DEFAULT NULL,
  `car_info_banner_1_h3` varchar(255) DEFAULT NULL,
  `car_info_banner_1_d3` varchar(255) DEFAULT NULL,
  
  `beyond_2_heading` varchar(255) DEFAULT NULL,
  `beyond_2_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_2_description` text,
  `beyond_2_black` varchar(10) DEFAULT 'false',
  
  `infovideo_2_url` text,
  `infovideo_2_semi` varchar(255) DEFAULT NULL,
  `infovideo_2_heading` varchar(255) DEFAULT NULL,
  `infovideo_2_desc` text,
  
  `beyond_3_heading` varchar(255) DEFAULT NULL,
  `beyond_3_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_3_description` text,
  `beyond_3_black` varchar(10) DEFAULT 'false',
  
  `car_info_banner_2_url` text,
  
  `beyond_4_heading` varchar(255) DEFAULT NULL,
  `beyond_4_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_4_description` text,
  `beyond_4_black` varchar(10) DEFAULT 'false',
  
  `order_now_heading` varchar(255) DEFAULT NULL,
  `order_now_url` text,
  `order_now_black` varchar(10) DEFAULT 'false',
  
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `modely_page` (
  banner_title, banner_url_desktop, banner_url_mobile, banner_description,
  banner_info_heading_1, banner_info_desc_1,
  banner_info_heading_2, banner_info_desc_2,
  banner_info_heading_3, banner_info_desc_3,
  banner_info_heading_4, banner_info_desc_4,
  banner_white,
  infovideo_1_url, infovideo_1_semi, infovideo_1_heading, infovideo_1_desc,
  beyond_1_heading, beyond_1_semi_heading, beyond_1_description, beyond_1_black,
  car_info_banner_1_url, car_info_banner_1_h1, car_info_banner_1_d1,
  car_info_banner_1_h2, car_info_banner_1_d2,
  car_info_banner_1_h3, car_info_banner_1_d3,
  beyond_2_heading, beyond_2_semi_heading, beyond_2_description, beyond_2_black,
  infovideo_2_url, infovideo_2_semi, infovideo_2_heading, infovideo_2_desc,
  beyond_3_heading, beyond_3_semi_heading, beyond_3_description, beyond_3_black,
  car_info_banner_2_url,
  beyond_4_heading, beyond_4_semi_heading, beyond_4_description, beyond_4_black,
  order_now_heading, order_now_url, order_now_black
) VALUES (
  'Model Y',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770094546/model-y_qaw0je.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770094546/model-y-mobile_rq1nxh.jpg',
  'Schedule a Demo Drive',
  '330 mi', 'Range (EPA est.)',
  '76 cu ft', 'Cargo Space',
  'AWD', 'Dual Motor',
  '1,020 hp', 'Peak Power',
  'true',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770094546/structure_zeey6l.jpg', 'Safety', 'Designed for Safety', 'Safety is the most important part of every Tesla. We design our vehicles to exceed safety standards',
  'A Place For Everything', 'Utility', 'Model Y provides maximum versatility—able to carry 7 passengers and their cargo. Each second row seat folds flat independently, creating flexible storage for skis, furniture, luggage and more. The liftgate opens to a low trunk floor that makes loading and unloading easy and quick. Chat with a Tesla Advisor to learn more about Model Y or schedule a demo drive today.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770094546/model-y-red_ex9mvk.jpg', '2', 'Independent motors digitally control torque to the front and rear wheels', '3.5 s', 'Quickest acceleration—from zero to 60 mph* in as little as 3.5 seconds', 'Weather', 'Unparalleled traction and control, in all weather conditions',
  'Dual Motor', 'All-Wheel Drive', 'Tesla All-Wheel Drive has two ultra-responsive, independent electric motors that digitally control torque to the front and rear wheels—for far better handling, traction and stability control. Model Y is capable in rain, snow, mud and off-road.', 'false',
  'https://res.cloudinary.com/doqeslffo/video/upload/v1770094552/model-y_axm7z8.mp4', 'Range', 'Go Anywhere', 'Model Y is fully electric, so you never need to visit a gas station again. If you charge overnight at home, you can wake up to a full battery every morning. ',
  'Future of Driving', 'Autopilot', 'Autopilot''s advanced safety and convenience features are designed to assist you with the most burdensome parts of driving.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770094546/model-y-interior_fsmmlk.jpg',
  'Built Around the Driver', 'Interior', 'With an elevated seating position and low dash, the driver has a commanding view of the road ahead. The interior of Model Y is simple and clean, with a 15-inch touch screen, immersive sound system and an expansive all-glass roof that creates extra headroom and provides a seamless view of the sky.', 'false',
  'Model S', 'https://res.cloudinary.com/doqeslffo/image/upload/v1770094547/model-y-ordernow_qnsjpp.jpg', 'false'
);

-- Solar Panel
CREATE TABLE `solarpanel_page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `banner_title` varchar(255) DEFAULT NULL,
  `banner_url_desktop` text,
  `banner_url_mobile` text,
  `banner_description` text,
  `banner_info_heading_1` varchar(255) DEFAULT NULL,
  `banner_info_desc_1` varchar(255) DEFAULT NULL,
  `banner_info_heading_2` varchar(255) DEFAULT NULL,
  `banner_info_desc_2` varchar(255) DEFAULT NULL,
  `banner_info_heading_3` varchar(255) DEFAULT NULL,
  `banner_info_desc_3` varchar(255) DEFAULT NULL,
  `banner_info_heading_4` varchar(255) DEFAULT NULL,
  `banner_info_desc_4` varchar(255) DEFAULT NULL,
  `banner_white` varchar(10) DEFAULT 'true',
  
  `infovideo_1_url` text,
  `infovideo_1_semi` varchar(255) DEFAULT NULL,
  `infovideo_1_heading` varchar(255) DEFAULT NULL,
  `infovideo_1_desc` text,
  
  `car_info_banner_1_url` text,
  
  `beyond_1_heading` varchar(255) DEFAULT NULL,
  `beyond_1_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_1_description` text,
  `beyond_1_black` varchar(10) DEFAULT 'false',
  
  `infovideo_2_url` text,
  `infovideo_2_semi` varchar(255) DEFAULT NULL,
  `infovideo_2_heading` varchar(255) DEFAULT NULL,
  `infovideo_2_desc` text,
  
  `car_info_banner_2_url` text,
  
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `solarpanel_page` (
  banner_title, banner_url_desktop, banner_url_mobile, banner_description,
  banner_info_heading_1, banner_info_desc_1,
  banner_info_heading_2, banner_info_desc_2,
  banner_info_heading_3, banner_info_desc_3,
  banner_info_heading_4, banner_info_desc_4,
  banner_white,
  infovideo_1_url, infovideo_1_semi, infovideo_1_heading, infovideo_1_desc,
  car_info_banner_1_url,
  beyond_1_heading, beyond_1_semi_heading, beyond_1_description, beyond_1_black,
  infovideo_2_url, infovideo_2_semi, infovideo_2_heading, infovideo_2_desc,
  car_info_banner_2_url
) VALUES (
  'Solar for Existing Roofs',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770094990/solarpanel_huwts0.jpg',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770094990/solarpanel-mobile_pzcq86.jpg',
  ' Lowest Cost Solar Panels',
  'Panel', 'Convert Sunlight to Energy',
  '$', 'Guaranteed Lowest Price for Solar',
  '24/7', 'Energy Monitoring',
  '1,020 hp', 'Peak Power',
  'false',
  'https://res.cloudinary.com/doqeslffo/video/upload/v1770094993/panel_pxfzhk.mp4', 'Design', 'Sliik and Durable', 'Our solar panels are low-profile and durable — quietly converting sunlight to energy for decades to come. Schedule a virtual consultation with an Energy Advisor to learn more.',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770094991/batteryback_fjdqzz.jpg',
  'Order and Installation', 'Power On', 'With a drag coefficient of just .208 Cd, the lowest on the planet, Model S is built for speed, endurance and range. Improved aerodynamics and a wider chassis offer more responsive performance so you can take corners quicker and with more confidence.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095197/solarproduction_atxssj.jpg', 'Efficiency', 'Maximum Solar Production', 'Generate the most energy possible, even on roofs with complicated angles and intermittent sunlight. Glass solar tiles and architectural-grade steel tiles, vent covers and ridge caps come together to form a roof that is both durable and powerful.',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095195/stock_ipc0wi.jpg'
);

-- Solar Roof
CREATE TABLE `solarroof_page` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `banner_title` varchar(255) DEFAULT NULL,
  `banner_url_desktop` text,
  `banner_url_mobile` text,
  `banner_description` text,
  `banner_info_heading_1` varchar(255) DEFAULT NULL,
  `banner_info_desc_1` varchar(255) DEFAULT NULL,
  `banner_info_heading_2` varchar(255) DEFAULT NULL,
  `banner_info_desc_2` varchar(255) DEFAULT NULL,
  `banner_info_heading_3` varchar(255) DEFAULT NULL,
  `banner_info_desc_3` varchar(255) DEFAULT NULL,
  `banner_info_heading_4` varchar(255) DEFAULT NULL,
  `banner_info_desc_4` varchar(255) DEFAULT NULL,
  `banner_white` varchar(10) DEFAULT 'true',
  
  `car_info_banner_1_url` text,
  
  `beyond_1_heading` varchar(255) DEFAULT NULL,
  `beyond_1_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_1_description` text,
  `beyond_1_black` varchar(10) DEFAULT 'false',
  
  `infovideo_1_url` text,
  `infovideo_1_semi` varchar(255) DEFAULT NULL,
  `infovideo_1_heading` varchar(255) DEFAULT NULL,
  `infovideo_1_desc` text,
  
  `infovideo_2_url` text,
  `infovideo_2_semi` varchar(255) DEFAULT NULL,
  `infovideo_2_heading` varchar(255) DEFAULT NULL,
  `infovideo_2_desc` text,
  
  `beyond_2_heading` varchar(255) DEFAULT NULL,
  `beyond_2_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_2_description` text,
  `beyond_2_black` varchar(10) DEFAULT 'false',
  
  `infovideo_3_url` text,
  `infovideo_3_semi` varchar(255) DEFAULT NULL,
  `infovideo_3_heading` varchar(255) DEFAULT NULL,
  `infovideo_3_desc` text,
  
  `car_info_banner_2_url` text,
  
  `beyond_3_heading` varchar(255) DEFAULT NULL,
  `beyond_3_semi_heading` varchar(255) DEFAULT NULL,
  `beyond_3_description` text,
  `beyond_3_black` varchar(10) DEFAULT 'false',
  
  `infovideo_4_url` text,
  `infovideo_4_semi` varchar(255) DEFAULT NULL,
  `infovideo_4_heading` varchar(255) DEFAULT NULL,
  `infovideo_4_desc` text,
  
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `solarroof_page` (
  banner_title, banner_url_desktop, banner_url_mobile, banner_description,
  banner_info_heading_1, banner_info_desc_1,
  banner_info_heading_2, banner_info_desc_2,
  banner_info_heading_3, banner_info_desc_3,
  banner_info_heading_4, banner_info_desc_4,
  banner_white,
  car_info_banner_1_url,
  beyond_1_heading, beyond_1_semi_heading, beyond_1_description, beyond_1_black,
  infovideo_1_url, infovideo_1_semi, infovideo_1_heading, infovideo_1_desc,
  infovideo_2_url, infovideo_2_semi, infovideo_2_heading, infovideo_2_desc,
  beyond_2_heading, beyond_2_semi_heading, beyond_2_description, beyond_2_black,
  infovideo_3_url, infovideo_3_semi, infovideo_3_heading, infovideo_3_desc,
  car_info_banner_2_url,
  beyond_3_heading, beyond_3_semi_heading, beyond_3_description, beyond_3_black,
  infovideo_4_url, infovideo_4_semi, infovideo_4_heading, infovideo_4_desc
) VALUES (
  'Solar Roof',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095197/solarroof_iwpywt.webp',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095198/solarroof-mobile_zx6njn.webp',
  'Transform your roof and produce clean energy',
  'Panel', 'Beautiful Solar',
  '25-Year', 'Tile Warranty',
  '24/7', 'Outage Protection',
  '1,020 hp', 'Peak Power',
  'true',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095201/solarroofbanner_pjq58w.webp',
  'Complement Your Home’s Aesthetic', 'Design', 'Install Solar Roof and power your home with a fully integrated solar and energy storage system. The glass solar tiles and steel roofing tiles look great up close and from the street, complementing your home’s natural styling. Schedule a virtual consultation with an Energy Advisor to learn more.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095201/energy-storage_ltp3wj.webp', 'Energy Storage', 'Protection Against Outages', 'Powerwall is a compact home battery that is bundled with Solar Roof, providing you with 24/7 energy security. It stores the energy you produce with Solar Roof so you can power your home anytime—at night or during an outage.',
  'https://res.cloudinary.com/doqeslffo/video/upload/v1770095202/durability_fr0jjr.webm', 'Durability', 'Take on the Elements', 'Solar Roof is comprised of both glass solar tiles and steel roofing tiles. Glass solar tiles produce energy, while architectural-grade steel tiles add longevity and corrosion resistance to your roof.',
  'Trusted Expertise', 'Installation', 'Our in-house team of energy professionals has installed nearly 4.0 GW of solar across approximately 480,000 roofs—cumulatively generating over 25.0 TWhs of clean energy. From design to power on, we take care of everything. Chat with an Energy Advisor to ask any questions about Solar Roof.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095197/solarproduction_atxssj.jpg', 'Efficiency', 'Maximum Solar Production', 'Generate the most energy possible, even on roofs with complicated angles and intermittent sunlight. Glass solar tiles and architectural-grade steel tiles, vent covers and ridge caps come together to form a roof that is both durable and powerful.',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095195/stock_ipc0wi.jpg',
  'Monitor and Optimize', 'Control', 'With the Tesla app, you can monitor your energy production in real time. Control your system from anywhere with instant alerts and remote access.', 'false',
  'https://res.cloudinary.com/doqeslffo/image/upload/v1770095199/payless_lppkkf.webp', 'Value', 'Pay Less for Electricity', 'Solar Roof helps pay for itself with the energy it produces. As a fully integrated system, Solar Roof can maximize your solar generation and help you take control of your monthly electricity bill.'
);
