import Hero from "@/components/common/Hero";

export const metadata = {
  title: "Electric Cars, Solar & Clean Energy | Tesla",
  description: "Generated by create next app",
};

export default function Home() {
  return <Hero />;
}
